#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""MostPop baseline for the POI recommendation datasets.

The expected input is the sequence file produced by
``poidata/extract_whole_user_buys.py``:

    check_times pois_different u_id u_pois u_times u_coordinates

Only ``u_pois`` is needed for MostPop. Each user's sequence is split
chronologically into train/test, POIs are ranked by their frequency in the
training split, and the same popularity list is recommended to every user.
By default, POIs already seen in a user's training history are filtered.
"""

from __future__ import print_function 

import argparse 
import csv 
import os 
from collections import Counter 


DEFAULT_DATA_ROOT =os .path .join (os .path .dirname (__file__ ),"poidata")


def parse_args ():
    parser =argparse .ArgumentParser (description ="Run a MostPop POI baseline.")
    parser .add_argument (
    "--dataset",
    default ="Foursquare",
    choices =["Foursquare","Gowalla"],
    help ="Dataset name under poidata/<dataset>/sequence/<dataset>.txt.",
    )
    parser .add_argument (
    "--file",
    default =None ,
    help ="Explicit sequence file path. Overrides --dataset.",
    )
    parser .add_argument (
    "--train-ratio",
    type =float ,
    default =0.8 ,
    help ="Chronological train ratio for each user sequence.",
    )
    parser .add_argument (
    "--topk",
    default ="5,10,15,20",
    help ="Comma-separated K values, for example: 5,10,20.",
    )
    parser .add_argument (
    "--no-filter-seen",
    action ="store_true",
    help ="Do not filter POIs that appeared in the user's training history.",
    )
    parser .add_argument (
    "--per-user-output",
    default =None ,
    help ="Optional CSV path for per-user metrics used by significance tests.",
    )
    return parser .parse_args ()


def resolve_sequence_file (args ):
    if args .file :
        return os .path .abspath (args .file )
    return os .path .join (
    DEFAULT_DATA_ROOT ,
    args .dataset ,
    "sequence",
    args .dataset +".txt",
    )


def load_user_sequences (sequence_file ):
    if not os .path .exists (sequence_file ):
        raise IOError (
        "Sequence file not found: {0}\n"
        "Expected a file generated by poidata/extract_whole_user_buys.py, "
        "for example poidata/Foursquare/sequence/Foursquare.txt.".format (
        sequence_file 
        )
        )

    user_ids =[]
    sequences =[]
    with open (sequence_file ,"r",newline ="")as handle :
        reader =csv .DictReader (handle ,delimiter =" ")
        if not reader .fieldnames or "u_pois"not in reader .fieldnames :
            raise ValueError ("Input file must contain a 'u_pois' column.")

        for idx ,row in enumerate (reader ):
            pois =[poi for poi in row ["u_pois"].split ("/")if poi !=""]
            if len (pois )>=2 :
                user_ids .append (row .get ("u_id",str (idx )))
                sequences .append (pois )

    if not sequences :
        raise ValueError ("No valid user POI sequences were found.")
    return user_ids ,sequences 


def split_sequences (sequences ,train_ratio ):
    if not 0.0 <train_ratio <1.0 :
        raise ValueError ("--train-ratio must be between 0 and 1.")

    train_sequences =[]
    test_sequences =[]
    for seq in sequences :
        split =int (len (seq )*train_ratio )
        split =min (max (split ,1 ),len (seq )-1 )
        train_sequences .append (seq [:split ])
        test_sequences .append (seq [split :])
    return train_sequences ,test_sequences 


def build_popularity_ranking (train_sequences ):
    counter =Counter ()
    for seq in train_sequences :
        counter .update (seq )
    if not counter :
        raise ValueError ("Training split is empty; cannot build MostPop ranking.")

    return [
    poi 
    for poi ,_ in sorted (counter .items (),key =lambda item :(-item [1 ],item [0 ]))
    ]


def recommend_for_user (popular_pois ,train_seq ,max_k ,filter_seen =True ):
    seen =set (train_seq )
    recs =[]
    for poi in popular_pois :
        if filter_seen and poi in seen :
            continue 
        recs .append (poi )
        if len (recs )==max_k :
            break 
    return recs 


def hit_vector (recommended ,test_seq ):
    test_items =set (test_seq )
    return [1 if poi in test_items else 0 for poi in recommended ]


def average_precision_at_k (hits ,num_relevant ):
    if num_relevant ==0 or sum (hits )==0 :
        return 0.0 
    precisions =[]
    cumulative_hits =0.0 
    for idx ,hit in enumerate (hits ,start =1 ):
        if hit :
            cumulative_hits +=1.0 
            precisions .append (cumulative_hits /idx )
    return float (sum (precisions )/num_relevant )


def ndcg_at_k (hits ,num_relevant ):
    if num_relevant ==0 or sum (hits )==0 :
        return 0.0 
    dcg =0.0 
    for idx ,hit in enumerate (hits ):
        if hit :
            dcg +=1.0 /log2 (idx +2 )
    ideal_len =min (num_relevant ,len (hits ))
    ideal_dcg =sum (1.0 /log2 (idx +2 )for idx in range (ideal_len ))
    return dcg /ideal_dcg if ideal_dcg >0 else 0.0 


def evaluate (user_ids ,recommendations ,test_sequences ,topks ):
    rows =[]
    per_user_rows =[]
    total_relevant =float (sum (len (seq )for seq in test_sequences ))
    num_users =float (len (test_sequences ))

    for user_id ,recs ,test_seq in zip (user_ids ,recommendations ,test_sequences ):
        user_row ={"user_id":user_id ,"num_test":len (test_seq )}
        for k in topks :
            hits =hit_vector (recs [:k ],test_seq )
            hit_sum =float (sum (hits ))
            user_row ["precision@{0}".format (k )]=hit_sum /k 
            user_row ["recall@{0}".format (k )]=(
            hit_sum /len (test_seq )if test_seq else 0.0 
            )
            user_row ["ap@{0}".format (k )]=average_precision_at_k (
            hits ,len (test_seq )
            )
            user_row ["ndcg@{0}".format (k )]=ndcg_at_k (hits ,len (test_seq ))
        per_user_rows .append (user_row )

    for k in topks :
        total_hits =0.0 
        per_user_ap =[]
        per_user_ndcg =[]

        for recs ,test_seq in zip (recommendations ,test_sequences ):
            hits =hit_vector (recs [:k ],test_seq )
            total_hits +=float (sum (hits ))
            per_user_ap .append (average_precision_at_k (hits ,len (test_seq )))
            per_user_ndcg .append (ndcg_at_k (hits ,len (test_seq )))

        recall =total_hits /total_relevant if total_relevant >0 else 0.0 
        precision =total_hits /(k *num_users )if num_users >0 else 0.0 
        f1 =(
        2.0 *recall *precision /(recall +precision )
        if recall +precision >0 
        else 0.0 
        )
        rows .append (
        {
        "K":k ,
        "Precision":precision ,
        "Recall":recall ,
        "F1":f1 ,
        "MAP":mean (per_user_ap ),
        "NDCG":mean (per_user_ndcg ),
        }
        )
    return rows ,per_user_rows 


def write_per_user_metrics (path ,per_user_rows ,topks ):
    out_dir =os .path .dirname (path )
    if out_dir and not os .path .exists (out_dir ):
        os .makedirs (out_dir )
    fieldnames =["user_id","num_test"]
    for k in topks :
        fieldnames +=[
        "precision@{0}".format (k ),
        "recall@{0}".format (k ),
        "ap@{0}".format (k ),
        "ndcg@{0}".format (k ),
        ]
    with open (path ,"w",newline ="")as handle :
        writer =csv .DictWriter (handle ,fieldnames =fieldnames )
        writer .writeheader ()
        writer .writerows (per_user_rows )


def log2 (value ):
    import math 

    return math .log (value ,2 )


def mean (values ):
    return float (sum (values )/len (values ))if values else 0.0 


def print_results (rows ):
    print ("")
    print ("MostPop results")
    print ("K\tPrecision\tRecall\t\tF1\t\tMAP\t\tNDCG")
    for row in rows :
        print (
        "{K}\t{Precision:.6f}\t{Recall:.6f}\t{F1:.6f}\t{MAP:.6f}\t{NDCG:.6f}".format (
        **row 
        )
        )


def main ():
    args =parse_args ()
    topks =[int (k .strip ())for k in args .topk .split (",")if k .strip ()]
    if not topks or min (topks )<=0 :
        raise ValueError ("--topk must contain positive integers.")

    sequence_file =resolve_sequence_file (args )
    user_ids ,sequences =load_user_sequences (sequence_file )
    train_sequences ,test_sequences =split_sequences (sequences ,args .train_ratio )
    popular_pois =build_popularity_ranking (train_sequences )

    max_k =max (topks )
    filter_seen =not args .no_filter_seen 
    recommendations =[
    recommend_for_user (popular_pois ,train_seq ,max_k ,filter_seen =filter_seen )
    for train_seq in train_sequences 
    ]

    print ("Sequence file: {0}".format (sequence_file ))
    print ("Users: {0}".format (len (sequences )))
    print ("Train check-ins: {0}".format (sum (len (seq )for seq in train_sequences )))
    print ("Test check-ins: {0}".format (sum (len (seq )for seq in test_sequences )))
    print ("Unique train POIs: {0}".format (len (popular_pois )))
    print ("Filter seen POIs: {0}".format (filter_seen ))

    rows ,per_user_rows =evaluate (user_ids ,recommendations ,test_sequences ,topks )
    print_results (rows )
    if args .per_user_output :
        write_per_user_metrics (args .per_user_output ,per_user_rows ,topks )
        print ("Per-user metrics saved to: {0}".format (args .per_user_output ))


if __name__ =="__main__":
    main ()
